// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: i.proto

package i

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type R struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R string `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *R) Reset() {
	*x = R{}
	if protoimpl.UnsafeEnabled {
		mi := &file_i_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *R) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R) ProtoMessage() {}

func (x *R) ProtoReflect() protoreflect.Message {
	mi := &file_i_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R.ProtoReflect.Descriptor instead.
func (*R) Descriptor() ([]byte, []int) {
	return file_i_proto_rawDescGZIP(), []int{0}
}

func (x *R) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

type Re struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Re string `protobuf:"bytes,1,opt,name=re,proto3" json:"re,omitempty"`
}

func (x *Re) Reset() {
	*x = Re{}
	if protoimpl.UnsafeEnabled {
		mi := &file_i_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Re) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Re) ProtoMessage() {}

func (x *Re) ProtoReflect() protoreflect.Message {
	mi := &file_i_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Re.ProtoReflect.Descriptor instead.
func (*Re) Descriptor() ([]byte, []int) {
	return file_i_proto_rawDescGZIP(), []int{1}
}

func (x *Re) GetRe() string {
	if x != nil {
		return x.Re
	}
	return ""
}

var File_i_proto protoreflect.FileDescriptor

var file_i_proto_rawDesc = []byte{
	0x0a, 0x07, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x01, 0x52, 0x12, 0x0c,
	0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x72, 0x22, 0x14, 0x0a, 0x02,
	0x52, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x72, 0x65, 0x32, 0x16, 0x0a, 0x01, 0x49, 0x12, 0x11, 0x0a, 0x06, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x63, 0x12, 0x02, 0x2e, 0x52, 0x1a, 0x03, 0x2e, 0x52, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2e, 0x2f,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_i_proto_rawDescOnce sync.Once
	file_i_proto_rawDescData = file_i_proto_rawDesc
)

func file_i_proto_rawDescGZIP() []byte {
	file_i_proto_rawDescOnce.Do(func() {
		file_i_proto_rawDescData = protoimpl.X.CompressGZIP(file_i_proto_rawDescData)
	})
	return file_i_proto_rawDescData
}

var file_i_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_i_proto_goTypes = []any{
	(*R)(nil),  // 0: R
	(*Re)(nil), // 1: Re
}
var file_i_proto_depIdxs = []int32{
	0, // 0: I.Interc:input_type -> R
	1, // 1: I.Interc:output_type -> Re
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_i_proto_init() }
func file_i_proto_init() {
	if File_i_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_i_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*R); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_i_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Re); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_i_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_i_proto_goTypes,
		DependencyIndexes: file_i_proto_depIdxs,
		MessageInfos:      file_i_proto_msgTypes,
	}.Build()
	File_i_proto = out.File
	file_i_proto_rawDesc = nil
	file_i_proto_goTypes = nil
	file_i_proto_depIdxs = nil
}
