// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: s.proto

package sameport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SameP_SP_FullMethodName = "/SameP/SP"
)

// SamePClient is the client API for SameP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SamePClient interface {
	SP(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type samePClient struct {
	cc grpc.ClientConnInterface
}

func NewSamePClient(cc grpc.ClientConnInterface) SamePClient {
	return &samePClient{cc}
}

func (c *samePClient) SP(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SameP_SP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SamePServer is the server API for SameP service.
// All implementations must embed UnimplementedSamePServer
// for forward compatibility
type SamePServer interface {
	SP(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSamePServer()
}

// UnimplementedSamePServer must be embedded to have forward compatible implementations.
type UnimplementedSamePServer struct {
}

func (UnimplementedSamePServer) SP(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SP not implemented")
}
func (UnimplementedSamePServer) mustEmbedUnimplementedSamePServer() {}

// UnsafeSamePServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SamePServer will
// result in compilation errors.
type UnsafeSamePServer interface {
	mustEmbedUnimplementedSamePServer()
}

func RegisterSamePServer(s grpc.ServiceRegistrar, srv SamePServer) {
	s.RegisterService(&SameP_ServiceDesc, srv)
}

func _SameP_SP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SamePServer).SP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SameP_SP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SamePServer).SP(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SameP_ServiceDesc is the grpc.ServiceDesc for SameP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SameP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SameP",
	HandlerType: (*SamePServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SP",
			Handler:    _SameP_SP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s.proto",
}
