server:
  http:
  # 先从环境变量中去读，读取不到就默认8000端口
    addr: 0.0.0.0:${HTTP_PORT:8000}
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123123@tcp(127.0.0.1:3306)/kratos?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

mode: dev
