// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: a.proto

package c

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Consul_SayHello_FullMethodName = "/Consul/SayHello"
)

// ConsulClient is the client API for Consul service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsulClient interface {
	SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type consulClient struct {
	cc grpc.ClientConnInterface
}

func NewConsulClient(cc grpc.ClientConnInterface) ConsulClient {
	return &consulClient{cc}
}

func (c *consulClient) SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Consul_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsulServer is the server API for Consul service.
// All implementations must embed UnimplementedConsulServer
// for forward compatibility
type ConsulServer interface {
	SayHello(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedConsulServer()
}

// UnimplementedConsulServer must be embedded to have forward compatible implementations.
type UnimplementedConsulServer struct {
}

func (UnimplementedConsulServer) SayHello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedConsulServer) mustEmbedUnimplementedConsulServer() {}

// UnsafeConsulServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsulServer will
// result in compilation errors.
type UnsafeConsulServer interface {
	mustEmbedUnimplementedConsulServer()
}

func RegisterConsulServer(s grpc.ServiceRegistrar, srv ConsulServer) {
	s.RegisterService(&Consul_ServiceDesc, srv)
}

func _Consul_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsulServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consul_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsulServer).SayHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Consul_ServiceDesc is the grpc.ServiceDesc for Consul service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consul_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Consul",
	HandlerType: (*ConsulServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Consul_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a.proto",
}
