// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: tls.proto

package tls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TReq) Reset() {
	*x = TReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TReq) ProtoMessage() {}

func (x *TReq) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TReq.ProtoReflect.Descriptor instead.
func (*TReq) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{0}
}

func (x *TReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *TResp) Reset() {
	*x = TResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TResp) ProtoMessage() {}

func (x *TResp) ProtoReflect() protoreflect.Message {
	mi := &file_tls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TResp.ProtoReflect.Descriptor instead.
func (*TResp) Descriptor() ([]byte, []int) {
	return file_tls_proto_rawDescGZIP(), []int{1}
}

func (x *TResp) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_tls_proto protoreflect.FileDescriptor

var file_tls_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x54,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x54, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x1c, 0x0a, 0x01, 0x54, 0x12, 0x17, 0x0a, 0x06, 0x54,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x05, 0x2e, 0x54, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x54,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x74, 0x6c, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tls_proto_rawDescOnce sync.Once
	file_tls_proto_rawDescData = file_tls_proto_rawDesc
)

func file_tls_proto_rawDescGZIP() []byte {
	file_tls_proto_rawDescOnce.Do(func() {
		file_tls_proto_rawDescData = protoimpl.X.CompressGZIP(file_tls_proto_rawDescData)
	})
	return file_tls_proto_rawDescData
}

var file_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tls_proto_goTypes = []any{
	(*TReq)(nil),  // 0: TReq
	(*TResp)(nil), // 1: TResp
}
var file_tls_proto_depIdxs = []int32{
	0, // 0: T.THello:input_type -> TReq
	1, // 1: T.THello:output_type -> TResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tls_proto_init() }
func file_tls_proto_init() {
	if File_tls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tls_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tls_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tls_proto_goTypes,
		DependencyIndexes: file_tls_proto_depIdxs,
		MessageInfos:      file_tls_proto_msgTypes,
	}.Build()
	File_tls_proto = out.File
	file_tls_proto_rawDesc = nil
	file_tls_proto_goTypes = nil
	file_tls_proto_depIdxs = nil
}
