// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Message      string `json:"message"`
	AccessToken  string `json:"accessToken"`
	AccessExpire string `json:"accessExpire"`
	RefreshAfter string `json:"refreshAfter"`
}

type SignupRequest struct {
	UserName   string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
	Gender     int    `json:"gender,option=0|1|2,default=0"`
}

type SignupResponse struct {
	Message string `json:"message"`
}

type UserInfoRequest struct {
	Username string `form:"username"`
}

type UserInfoResponse struct {
	Username string `json:"username"`
	Age      int    `json:"age"`
	Gender   int64  `json:"gender"`
}
