// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: 1.proto

package homework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomeWokrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (x *HomeWokrRequest) Reset() {
	*x = HomeWokrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file__1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeWokrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeWokrRequest) ProtoMessage() {}

func (x *HomeWokrRequest) ProtoReflect() protoreflect.Message {
	mi := &file__1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeWokrRequest.ProtoReflect.Descriptor instead.
func (*HomeWokrRequest) Descriptor() ([]byte, []int) {
	return file__1_proto_rawDescGZIP(), []int{0}
}

func (x *HomeWokrRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HomeWokrRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type HomeWorkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int32 `protobuf:"varint,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
}

func (x *HomeWorkResponse) Reset() {
	*x = HomeWorkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file__1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeWorkResponse) ProtoMessage() {}

func (x *HomeWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file__1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeWorkResponse.ProtoReflect.Descriptor instead.
func (*HomeWorkResponse) Descriptor() ([]byte, []int) {
	return file__1_proto_rawDescGZIP(), []int{1}
}

func (x *HomeWorkResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File__1_proto protoreflect.FileDescriptor

var file__1_proto_rawDesc = []byte{
	0x0a, 0x07, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2d, 0x0a,
	0x0f, 0x48, 0x6f, 0x6d, 0x65, 0x57, 0x6f, 0x6b, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c,
	0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x59, 0x22, 0x24, 0x0a, 0x10,
	0x48, 0x6f, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53,
	0x75, 0x6d, 0x32, 0x3e, 0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x32,
	0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x57,
	0x6f, 0x6b, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x48, 0x6f, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__1_proto_rawDescOnce sync.Once
	file__1_proto_rawDescData = file__1_proto_rawDesc
)

func file__1_proto_rawDescGZIP() []byte {
	file__1_proto_rawDescOnce.Do(func() {
		file__1_proto_rawDescData = protoimpl.X.CompressGZIP(file__1_proto_rawDescData)
	})
	return file__1_proto_rawDescData
}

var file__1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file__1_proto_goTypes = []any{
	(*HomeWokrRequest)(nil),  // 0: pb.HomeWokrRequest
	(*HomeWorkResponse)(nil), // 1: pb.HomeWorkResponse
}
var file__1_proto_depIdxs = []int32{
	0, // 0: pb.HomeWork.Add:input_type -> pb.HomeWokrRequest
	1, // 1: pb.HomeWork.Add:output_type -> pb.HomeWorkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__1_proto_init() }
func file__1_proto_init() {
	if File__1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file__1_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HomeWokrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__1_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HomeWorkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__1_proto_goTypes,
		DependencyIndexes: file__1_proto_depIdxs,
		MessageInfos:      file__1_proto_msgTypes,
	}.Build()
	File__1_proto = out.File
	file__1_proto_rawDesc = nil
	file__1_proto_goTypes = nil
	file__1_proto_depIdxs = nil
}
