// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: i.proto

package i

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	I_Interc_FullMethodName = "/I/Interc"
)

// IClient is the client API for I service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IClient interface {
	Interc(ctx context.Context, in *R, opts ...grpc.CallOption) (*Re, error)
}

type iClient struct {
	cc grpc.ClientConnInterface
}

func NewIClient(cc grpc.ClientConnInterface) IClient {
	return &iClient{cc}
}

func (c *iClient) Interc(ctx context.Context, in *R, opts ...grpc.CallOption) (*Re, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Re)
	err := c.cc.Invoke(ctx, I_Interc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IServer is the server API for I service.
// All implementations must embed UnimplementedIServer
// for forward compatibility
type IServer interface {
	Interc(context.Context, *R) (*Re, error)
	mustEmbedUnimplementedIServer()
}

// UnimplementedIServer must be embedded to have forward compatible implementations.
type UnimplementedIServer struct {
}

func (UnimplementedIServer) Interc(context.Context, *R) (*Re, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Interc not implemented")
}
func (UnimplementedIServer) mustEmbedUnimplementedIServer() {}

// UnsafeIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IServer will
// result in compilation errors.
type UnsafeIServer interface {
	mustEmbedUnimplementedIServer()
}

func RegisterIServer(s grpc.ServiceRegistrar, srv IServer) {
	s.RegisterService(&I_ServiceDesc, srv)
}

func _I_Interc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(R)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServer).Interc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: I_Interc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServer).Interc(ctx, req.(*R))
	}
	return interceptor(ctx, in, info, handler)
}

// I_ServiceDesc is the grpc.ServiceDesc for I service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var I_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "I",
	HandlerType: (*IServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Interc",
			Handler:    _I_Interc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "i.proto",
}
